[package]
name = "vessel-macros"
version = "0.1.0"
authors = ["Jay Nagpaul <jaynagpaul@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
http = "0.1.13"
quote = "0.6.9"

[dependencies.syn]
version = "0.15.18"
features = ["full"]
